on:
  push:
    tags:
      - '*'

permissions:
  # To upload archives as GitHub Releases
  contents: write
  # To push Docker images to GitHub
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      -
        uses: actions/checkout@v2
        with:
          # All history, required for goreleaser
          fetch-depth: 0
      -
        # For TagBody, TagSubject or TagContents fields in goreleaser's templates
        run: git fetch --force --tags

      - run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u docker --password-stdin

      -
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.9.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
